css:
  options:
    :charset: utf-8
  files:
    - base.css
    - button.css
    - checkbox.css
    - colormenubutton.css
    - colorpalette.css
    - combobox.css
    - dialog.css
    - dialogs.css
    - fontoption.css
    - icon.css
    - inputcolorpicker.css
    - inputunitchanger.css
    - layout.css
    - menu.css
    - menubutton.css
    - menuitem.css
    - menuseparator.css
    - message.css
    - notification.css
    - option.css
    - optionmenu.css
    - propertypane.css
    - splitbutton.css
    - tabpane.css
    - toolbar.css
    - toolbox.css
    - view.css
    - workspace.css
  output: app.css